### ISSUE TITLE
試合開始の判定をクライアント側でやる

### ISSUE THREAD

**Issue by fuu38** [Chaha1n/Shugiou-Client#10]
ブラウザ側で試合終了の判定を行うのめちゃめんどくさいことが判明したので、クライアント側でやる。(厳密には試合終了ではないけれど)
ブラウザ側は、value:100を受け取ると「このクライアントの臭いが100%に到達したので、試合終了だな」と判断して接続を切るように設定した。
そのため、クライアント側で
1. 勝利条件を決めておく(例:毎秒の臭いの合計値が5000に達したら終了)
1.  現在何%進んだかを求めpublishする(例:今合計が500だから、全体の10%なので、value:10をpublishしよう！)
という実装をしたい。

**Comment by fuu38** [comment]
ペンでやってみたとき200→400〜500みたいな変化だった。デモの尺とか考えると長くて20秒くらいで終わらせたい(ここは実際やってみて調整ポイント。)
すると、増分が250/sとして4000〜5000くらいで終わらせるのが良さそう？

**Comment by plmwa** [comment]
試合の終了判定は#12でやることにした

**Comment by plmwa** [comment]
終了判定の中に出力の値変更も含まれているため
